set_property IOSTANDARD LVCMOS33 [get_ports CAN_0_0_rx]
set_property IOSTANDARD LVCMOS33 [get_ports CAN_0_0_tx]
set_property IOSTANDARD LVCMOS33 [get_ports {led2_sp1_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led2_sp1_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led2_sp1_tri_o[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_2bit_tri_i[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_2bit_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_sda_io]
set_property PACKAGE_PIN L21 [get_ports CAN_0_0_rx]
set_property PACKAGE_PIN L22 [get_ports CAN_0_0_tx]
set_property PACKAGE_PIN T22 [get_ports {led2_sp1_tri_o[0]}]
set_property PACKAGE_PIN T21 [get_ports {led2_sp1_tri_o[1]}]
set_property PACKAGE_PIN U22 [get_ports {led2_sp1_tri_o[2]}]


set_property PACKAGE_PIN G22 [get_ports {sw_2bit_tri_i[1]}]
set_property PACKAGE_PIN F22 [get_ports {sw_2bit_tri_i[0]}]

set_property PACKAGE_PIN Y11 [get_ports IIC_0_0_scl_io]
set_property PACKAGE_PIN AA11 [get_ports IIC_0_0_sda_io]
